# Generated by Django 3.2 on 2021-04-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='name',
            new_name='title',
        ),
    ]
